[package]
name = "quelora-markdown-parser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
pulldown-cmark = { version = "0.12", default-features = false, features = ["html"] }
regex-lite = "0.1"
once_cell = "1"

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
codegen-units = 1